<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HP-dx7500" name="Default test" tests="1" failures="1" timestamp="29 May 2018 01:35:51 GMT" time="48.674" errors="0">
  <testcase name="CPNI_SpectrumPrimary" time="38.779" classname="test_Cases.CPNI_Tests">
    <failure type="java.lang.AssertionError" message="Save Password Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Save Password Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at utilities.Framework.editPasswordInfo(Framework.java:102)
	at test_Cases.CPNI_Tests.CPNI_SpectrumPrimary(CPNI_Tests.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CPNI_SpectrumPrimary -->
</testsuite> <!-- Default test -->
